### PR TITLE
login-page updated

### PR DESCRIPTION
**Pull request by priyabr4t**
login page updated

### CODE REVIEW

**Comment by chee-zer** [comment]
package-lock.json ko kyun push kar rahe ho yahan :sob:

**Comment by neoandmatrix** [comment]
> package-lock.json ko kyun push kar rahe ho yahan 😭

image

**Comment by chee-zer** [comment]
> 
> image

ah mereko laga sirf package.json is sufficient. I guess version ambiguity create ho jaegi then

**Comment by neoandmatrix** [comment]
yes push karna is compulsory docs me hi hai.

**Review by neoandmatrix — APPROVED** [review]

**Pull request merged**
